version: 0.2

phases:
  build:
    commands:
      - chmod +x run.sh
      - ./run.sh
      - java -jar /veracode/veracode-wrapper.jar -action uploadandscan -vid $VID -vkey $VKEY -appname pocbash -createprofile false -version $(date +%Y-%m-%d-%H:%M) -filepath target/verademo.war -sandboxname "Development Sandbox" -createsandbox true
